# Generated by Django 5.0 on 2023-12-27 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, default=None, max_length=40, validators=[django.core.validators.EmailValidator], verbose_name='Почта')),
            ],
        ),
    ]
