# Generated by Django 5.0.1 on 2024-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=250,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        max_length=250,
                        unique=True,
                        verbose_name="Ссылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("-title",),
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("is_active", "-title"),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
