# Generated by Django 5.0.1 on 2024-01-12 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0004_remove_item_id_alter_item_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vip",
            fields=[
                (
                    "priority",
                    models.IntegerField(
                        blank=True, db_index=True, default=1, verbose_name="Приоритет"
                    ),
                ),
                (
                    "expired",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="дата и время истичения",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        blank=True,
                        default="",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_app.item",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vip объявление",
                "verbose_name_plural": "Vip объявлении",
                "ordering": ("priority", "expired"),
            },
        ),
    ]
