# Generated by Django 5.0.1 on 2024-01-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0005_vip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
