# Generated by Django 5.0.1 on 2024-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0006_alter_categoryitem_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
