# Generated by Django 5.0.1 on 2024-01-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0007_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="avatar",
            field=models.ImageField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                upload_to="item/avatars",
                verbose_name="Аватар",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="file",
            field=models.FileField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                upload_to="item/files",
                verbose_name="Инструкция",
            ),
        ),
    ]
