# Generated by Django 5.0.1 on 2024-01-23 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0013_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
